### ISSUE TITLE
issue with the screen 

### ISSUE THREAD

**Issue by younessazel** [maxritter/diy-thermocam#38]
hello;
i have a problem with the screen ; i followed all steps of the firmware update guide and the thermocam lights up, but it shows me this message, although I touch the screen it does not change , i don't really know what is the problem,  please ; I am looking for help :
![43dd4d2c-07af-46ef-b1c4-aa598a797d4b](https://user-images.githubusercontent.com/33829975/40428655-49d0d6ea-5e90-11e8-8480-ce31beb159f9.jpg)
![9202ff87-776c-4381-b8c2-ac85479c8baf](https://user-images.githubusercontent.com/33829975/40428658-4a35d770-5e90-11e8-88c6-231ee59cbf0d.jpg)

**Comment by maxritter** [comment]
Somehow the firmware expects you are using a Cheap-Thermocam V4 hardware build.. But I assume you built the DIY-Thermocam V2? 

Make sure you use the right version of the MLX90614 spot sensor, which is MLX90614-BCF and the resistive version of the touch display. Otherwise it can not detect the right hardware version.
