### ISSUE TITLE
Onboard SD-card use

### ISSUE THREAD

**Issue by Nprod** [maxritter/diy-thermocam#58]
Both the Teensy and the LCD module from buydisplay have microSD card readers on them, but none of them are seen by the firmware. Seems a little redundant - is it possible to use one of them instead? MicroSD cards are more common than their larger SD counterparts these days anyway.

**Comment by maxritter** [comment]
Dear @Nprod,

due to driver conflicts with multiple devices sharing the SPI bus and the wiring of the mentioned microSD readers on the LCD and Teensy module, it is not possible to use them with the current FW implementation.

Thats why it was required to add an aditional SD slot on the PCB. The Thermocam uses an SD to microSD adapter, so you should be able to utilize your microSD cards in the same way and it's easier to put them in/out of the slot.

Best,
Max
